### ISSUE TITLE
enable xarray-vtk data structures interoperable without copying 

### ISSUE THREAD

**Issue by aashish24** [Kitware/pan3d#1]
@rabernat Could you share the Jupyter notebook that you created for the climate simulation data rendering using PyVista?

**Comment by rabernat** [comment]
Sorry for the delay! Here is one of the notebooks I made.

https://notebooksharing.space/view/c792283902a641e94e89de702aa00afd2b00ab68ae5926dfa06b53d890671bb5

**Comment by aashish24** [comment]
this is very helpful @rabernat. Could you share (or point to) the dataset as well?
