### ISSUE TITLE
Explore feasibility of simplifying vtk symbol imports

### ISSUE THREAD

**Issue by johnkit** [Kitware/pan3d#105]
Needs more definition, but the underlying idea is to copy what Vedo does for importing objects. Most of the logic is in https://github.com/marcomusy/vedo/blob/master/vedo/vtkclasses.py. The main features of interest
* internal module lookup for each class
* class name aliasing (e.g. "vtk" prefix not required)

**Comment by jourdain** [comment]
outside the scope of pan3d. closing
