### ISSUE TITLE
Viewer capabilities

### ISSUE THREAD

**Issue by jourdain** [Kitware/pan3d#12]
- [x] Load Zarr file
- [ ] Create Grid and link zarr array to grid
   - [x] Image Data
   - [x] Rectilinear grid
      - [x] Use array for xyz point
      - [x] Use array for xyz cells
   - [x] Add point data 
      - [ ] Support extra dimension for time
   - [x] Add cell data 
      - [ ] Support extra dimension for time
- [x] Viewer controls
   - [x] Color by Array
   - [x] Toggle edge visibility
   - [x] Reset camera
   - [ ]  Level of detail slider
 - [ ] Load HDF5 file
 - [ ] Jupyter Kernel level integration for restore and save

**Comment by jourdain** [comment]
<img width="1594" alt="Screen Shot 2022-09-07 at 17 09 29" src="https://user-images.githubusercontent.com/294518/188999491-418bd556-b0d8-4fa7-933b-1a3b02fc72a5.png">
<img width="1594" alt="Screen Shot 2022-09-07 at 17 10 29" src="https://user-images.githubusercontent.com/294518/188999494-262fc47a-173f-4373-8490-ae185e11ca30.png">
<img width="1594" alt="Screen Shot 2022-09-07 at 17 12 49" src="https://user-images.githubusercontent.com/294518/188999498-298fc2b7-aee2-4bef-9d26-edee3c8918cd.png">

**Comment by jourdain** [comment]
@johnkit please add item in the todo list

@aashish24 let's figure out what are the next priorities and timeline. So far I did the bare minimum with the time I had available. Maybe @banesullivan can push some of it forward. But for now, I won't be able to push anything more this week.

**Comment by aashish24** [comment]
This looks great. I edited (if that was what you were asking) the to-do list at the top. I think the next step would be the LOD slider that changes the resolution of the Mesh. And then, we need to look into if we could do something similar for the HDf5 datasets.

**Comment by banesullivan** [comment]
> Jupyter Kernel level integration for restore and save

This subtask is not feasible with trame at this time without major work to `wslink` and `trame`
