### ISSUE TITLE
Viewer: use geovista?

### ISSUE THREAD

**Issue by banesullivan** [Kitware/pan3d#18]
It would be nice to use geovista in the Pan3D viewer to show the datasets in a global context

ref https://github.com/pyvista/pyvista-xarray/blob/main/examples/level_of_detail_geovista.py

![180887602-e1c71e32-8c0f-4cee-a587-ae9d226a571c](https://user-images.githubusercontent.com/22067021/197833307-e198f353-c613-441a-8420-b478abb19581.png)

**Comment by jourdain** [comment]
We should be able to deploy several apps on that same server.

**Comment by banesullivan** [comment]
Okay great so one could have global plotting like this and the others normal
