### ISSUE TITLE
Untangle dataset_builder from the viewer part

### ISSUE THREAD

**Issue by jourdain** [Kitware/pan3d#52]
Right now, the dataset_builder requires trame, but in reality, it should not.
If you are just looking at a data source, the GUI and server part should not be required.
Also, it will be nicer architecture wise to differentiate the "data processing" part with the "user interaction".

**Comment by annehaley** [comment]
There are a lot of ways we can go about this. My first idea is that we would have a second class `DatasetViewer` or just `Viewer`. Usage could look like this:
```
from pan3d import DatasetBuilder, DatasetViewer
builder = DatasetBuilder()
viewer = DatasetViewer(builder)

builder.import_config(config)
viewer
```

Does this align with your vision @jourdain? I am open to other architectures as well.

**Comment by jourdain** [comment]
Yes, I was thinking as a class separation like that. 

But most likely with method in DatasetBuilder like below

```python
@property
def viewer(self):
   if self._viewer is None:
      from pan3d import DatasetViewer
      self._viewer =  DatasetViewer(self)

   return self._viewer
```

**Comment by jourdain** [comment]
Also, ideally a server could be provided to the dataset builder so the viewer could be using an existing one instead of creating a new one or stealing one that is used by someone else...

**Comment by annehaley** [comment]
> Also, ideally a server could be provided to the dataset builder so the viewer could be using an existing one instead of creating a new one or stealing one that is used by someone else...

Ok, I can do that. Should I import `trame_server.core.Server` for the typing of that kwarg, or try to avoid importing that completely and just type it as any?

**Comment by jourdain** [comment]
No trame import in DatasetBuilder

Something like 

```python
class DatasetBuilder:
    def __init__(self, trame_server=None):
          self._trame_server = trame_server
          self._viewer = None

   @property
   def viewer(self):
      if self._viewer is None:
         from pan3d import DatasetViewer
         self._viewer =  DatasetViewer(self._trame_server, self)

      return self._viewer
    
```

trame_server can technically be a string or the Server type... So I guess thanks to data typing you are forced to import it? Is there a way to not import trame? Like `str | obj`?

**Comment by jourdain** [comment]
use `any`... We should make `get_server` maybe more robust down the road.
