### ISSUE TITLE
vtk-xarray interop prototype

### ISSUE THREAD

**Issue by johnkit** [Kitware/pan3d#7]
This is a development task for prototyping an xarray accessor and related glue logic for constructing vtkDataObject instances from xarray data array input. Should be able to demo this in notebooks, for example, in one line, for example:

```
vtk_mesh = xr_to_vtk(data_array)
```

**Comment by jourdain** [comment]
would it be possible to have the following instead?

```python
>>> ds = xr.Dataset({"longitude": np.linspace(0, 10), "latitude": np.linspace(0, 20)})
>>> ds.vtk.object
RectilinearGrid(...)  # or whatever vtk/pyvista data type
>>> ds.pyvista.plot()
# ... pyvista is used for 3D rendering pipeline
```

**Comment by banesullivan** [comment]
That is what I'm currently doing where `ds.vtk.object` would effectively be an alias for `ds.pyvista.object`

**Comment by jourdain** [comment]
Also I don't think we agreed on using PyVista for the data interface. That was indeed you initial suggestion but ideally we want to use the new VTK python extension to natively support accessor API.

**Comment by jourdain** [comment]
I would have that alias be the other way around if possible. I mean it could be fine to do what you are suggesting for a quick and dirty prototyping but for long term, we really need to get things into vtk. 

And with that new Python interface, it does not need to be committed inside vtk on day 1.

**Comment by banesullivan** [comment]
> but for long term, we really need to get things into vtk.

What exactly do we need to get into VTK? This is still unclear to me.

**Comment by jourdain** [comment]
Ideally the Python classes that extend the various vtk factories. But they could be defined outside of vtk at first during the dev process.

**Comment by aashish24** [comment]
> I would have that alias be the other way around if possible. I mean it could be fine to do what you are suggesting for a quick and dirty prototyping but for long term, we really need to get things into vtk.

I agree
