### ISSUE TITLE
Potential viewer bugs

### ISSUE THREAD

**Issue by annehaley** [Kitware/pan3d#81]
I went through alot of the visualization features and everything works fine for me. There were a couple things that did not work as expected, though they might not be due to this PR (I didn't go back and compare with pan3d:main branch).

* The "Import" feature does not work for me. When I click the "Import" button, the viewer displays the "Import File Select" dialog. I can browse to my config file ok. When I click the dialog's "Import" button, the dialog remains displayed and the view does not update. (No messages on the terminal or js console.) Here's the config file I tested with: [pan3d_state.json](https://github.com/Kitware/geo-trame/files/15470116/pan3d_state.json)

* This might be more of a feature request: When the user switches to cartography mode, I think we should change the center of rotation to the earth's center.

_Originally posted by @johnkit in https://github.com/Kitware/geo-trame/issues/78#issuecomment-2135177191_

**Comment by johnkit** [comment]
1. Import problems were operator error - needed latest version of pyvista-xarray
2. User can change center of rotation with the "Reset Camera" control on the toolbar
