### ISSUE TITLE
Widgets occluding others depending on the sequence of actions

### ISSUE THREAD

**Issue by ayenpure** [Kitware/pan3d#86]
Depending on the sequence of actions, certain widgets occlude others.
This can be easily worked around by closing the occluding widgets to access the desired ones, but is a minor inconvenience.

Two examples below:

1. Trying to change the colormap first, but then immediately trying to change the axis properties
![Screenshot from 2024-07-15 10-21-24](https://github.com/user-attachments/assets/96124c9e-df89-492e-9d4c-08cc1d3d5849)

2. Trying to change the bounds configuration and then immediately trying to change data arrays
![Screenshot from 2024-07-15 10-27-25](https://github.com/user-attachments/assets/793c8aa5-61b8-4f2e-b8da-f27381886144)

**Comment by johnkit** [comment]
Seems like we should add some options to the "render" part of DatasetBuilder's config, for setting the scalar bar visibility, location (orientation, origin, length, thickness, maybe in parametric coords?)
