### ISSUE TITLE
Investigate vtk-numpy interoperation

### ISSUE THREAD

**Issue by johnkit** [Kitware/pan3d#9]
The long-term goal is to enhance VTK to support interoperation between mainstream scientific data formats and vtk grids (structured, rectilinear and, eventually, unstructured grids). This task begin looking at using the python override feature recently added to vtk:master as the basis for prototype vtk-numpy capabilities.

**Comment by banesullivan** [comment]
Steps to move forward in first phase of this work

- [ ] Clean up PR upstream in PyVista to isolate the core data model package
- [ ] Create new repository and copy PyVista git history in full
- [ ] git-filter-repo to clean the history to just the core subpackage
- [ ] Script to search for commit messages referencing commits or PRs in PyVista and fix with links as best we can
- [ ] Rename classes, change package name, get code working
- [ ] Add/update tests and check coverage
