### ISSUE TITLE
Feature Request: Any way to insert geojson?

### ISSUE THREAD

**Issue by johnkit** [Kitware/pan3d#95]
After some machinations, I was able to display some possibly-interesting data from the "eraint_uvz" dataset, which is read by the `import_conifg_xarray.ipynb` example notebook. After deriving the magnitude of air speed (_how_ I do that is another story), the uppermost level (850 millibar) shows a pattern that _might_ be indicative of major trade winds.

It would be quite handy if I could also display country outlines in this same view for visual context. Given that the rendering is done by vtk, I presume there is no practical way to display a geojson file. Is it possible to add a feature like that to vtk.js?

![screenshot](https://github.com/user-attachments/assets/931372e1-5b64-4425-93df-7dacc0e4c65b)

**Comment by jourdain** [comment]
If you can convert a geojson to a polydata, then you are good to go. Either way you need to map the coordinate to our world one.

**Comment by johnkit** [comment]
Feature request including in #107
